# Copyright (C) 2017, 2018 Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

language: python
dist: trusty
sudo: required
notifications:
  email: false
  irc:
    channels:
      - "irc.libera.chat#risu"
    on_success: change

python:
- '3.5'

before_install:
- pip install tox
- pip install python-coveralls

addons:
  apt:
    update: true
  sonarcloud:
    organization: "citellus"
    token:
      secure: "lW5hXsC1P3wZKeL1TeQai64qYnCpODA7fK8fYbnB42O5cApn/lJtNQyeYFFP1m0tC/ikUn7OPPCSOC06491POqg/CeZ7jDyOyyQ7wPVCoOGotxtC9f1F6MMQd/g6ahUD3IO6lUsJNy2U28307Daj01S5EsrouDqK+Cq7CN7/z/4DT/vFcop3pIjDW4ZDjMqERIGUkb4GslPfTNMPXSWqA2rbPNMGyuqBaPmjnsynNUBbMSXSz7Kz8396XPuMZyl3ZPfdiA2xqn+VJOES/qJNlq8Se059f+2pvqWnOxoqSQb7bKmwcslRXfVJrL13Do+BhUZt3/TwghJOMPTzyxf+LDfesEA7feWFXQgE7fWAA49H2ZkGDi9XepH8prsI3sdLiPpFcJzkKTkzSh060BeF6r/a6/1HnrL2QrYQ5QOB11z6tDwHxMC7qYr7lsFgDnAO0Y7Rf+FLWB8CB4MSxAp9rwcwdzmssOedrjbzwZRWAjzhzwIbToHyQ2R2xtdKRtG/gNE0pu6WlndmBVOnEd3wYUctdqsMszNHH8muXx6UdwNUv/zyrETQHiMO53YZe9IilLWeuyhtqvNM5WGwv7Rrml4KvGzRCJLN+6dmAxwUl5NA0S/CNndSQ4C1r3LDh1yo0LeMWyNkMep3OHvQf9ENjidKlPDwXkcuvzNe1Hy9Pmk="

script:
- tox
# - sonar-scanner

# deploy:
#   provider: pypi
#   user: citellus
#   distributions: sdist
#   password:
#     secure: gFTqF7ykv230d3M0Ql99TY3mXGEwYZBfpQKxjxhBxaI+lT4VpUhCz6NpoZ+B5JLBF9s0aHUuBli1Fhf6fhRgbPm8aWiihvw5g7YxSR9BWcxV6C0qjptrx7nTEh+5UO+ohpWIDnPVX2hwz3fj9gxCF1y/12bEWGMc1MCmrf97NBbA8+LXDP3fI5Oz9PK1qTwOL2jv3eYI2jexq/wfA643OQqqDZ0MHRwtjAeMjOaMuQ4DQGHHn03Ht6X83LxNn24YZ47jo9dKJOmg3ZxelLpA6ZGwaTaXjIUdv4gDCXtrTA4UDHL49d4hCqOcEbq+8b9hemRC/lpy00sw4cH9agskDVRjolzhUwzqQBrwG7Os/9wMJZwb8WAqbEUNjJNdkp87TF/N5MY4iCFQvl3ITmDC3j0n1IZWqH7tTv3NAu6nl24HSECdfGzdLVdAN0aduug2rN2Xm+657P4nNpM6u4WFJvC2hhHD+MxYnhdCrgUNc3WH9vu4u4i4pEYKvwHIPRzeKRg+wj6NtiMcm49N+aR+RXo5Ym3TH321CP10ZACKx8MQCqo//cCliViTgeC/FbP+mWvJp/EOXuqyylaMihjlnHELcp+h3Q+P5aNNSTpvo+x5gPN4RZB2KuNZEDn7lXKVE50fx5VsYXpe70bbVJH0TLLFVSfHg2IjGXsBMgzzeC8=
#   on:
#     branch: master

after_success:
- coveralls
